### ISSUE TITLE
FR : Non following similar Char

### ISSUE THREAD

**Issue by Yago** [AjayMT/bruteforce#1]
@AjayMT First I would like to say that this is a very usefull module ! :+1: 

In my use case, I want to find all the permutations of a given array of characters, but without the same two following characters.

For example : 

```javascript
var bf = require('bruteforce');

bf({
  len: 3,
  chars: ['a', 'b', 'c'],
  step: console.log
});
```

I would like to have only : 

```
abc
acb
bac
bca
cab
cba
```

What do you think about adding a new parameter ?

**Comment by AjayMT** [comment]
Hey @Yago 

Sorry for not responding to this earlier, I haven't had a lot of time to spare. I'll definitely look into implementing this feature when I can :)

**Comment by Yago** [comment]
Great ! Thanks :smile::+1:
